version: "3.8"

services: 
  postgres:
    image: postgres:latest
    container_name: jet-ai-postgres
    environment:
      POSTGRES_DB: jet-ai
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/gavinsidhu/Documents/Projects/jet-ai/jet_facts.csv:/data/jet_facts.csv
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
